[cin7]
base_url = "https://api.cin7.com/api/"
api_username = "HardwareDirectNZ"
api_key = "ca8dbaf7006441319ea8073e40955461"
branch_hamilton_id = 230
branch_hamilton_default_member = 230

branch_avondale_id = 3
branch_avondale_default_member = 3
